### ISSUE TITLE
[RFE] Make WSJT-X Flatpak file system more sandboxed

### ISSUE THREAD

**Issue by AsciiWolf** [flathub/edu.princeton.physics.WSJTX#21]
We could consider removing the full home file system access for WSJT-X similar to what I have recently did [with QSSTV](https://github.com/flathub/net.qsl.QSSTV/commit/f94c47f3c2156bf375b8c4256d8c0d832f04e609). It looks like that the "Open" dialog works fine using XDG desktop portal and there is no obvious reason for storing the config and data files of WSJT-X directly inside user's home.

**Comment by xylo04** [comment]
Fine with me! 🚀

**Comment by AsciiWolf** [comment]
Cool! :-) I will send a PR.
